/**
 * GENERATED from the Ruby gem (Pubid.prefix_flavors after
 * eager_load_flavors!) — the prefix→flavors routing table. Regenerate
 * from the pubid gem with:
 *   bundle exec ruby -e 'require "pubid"; Pubid.eager_load_flavors!;
 *     require "json"; puts JSON.pretty_generate(Pubid.prefix_flavors
 *     .transform_values { |v| v.sort })'
 * Do not edit by hand.
 *
 * Used by the gost flavor's foreign-adoption routing (prefix_owner in
 * index.ts): the single flavor owning the longest matching prefix parses
 * the adopted identifier; joint prefixes (ISO/IEC, ANSI/AMCA…) fall
 * through to the sorted fallback loop.
 */
export const PREFIX_ROUTES: Record<string, string[]> = {
  "10.": ["doi"],
  "3GPP": ["tgpp"],
  "AI": ["nist"],
  "AMCA": ["amca"],
  "AMS": ["nist"],
  "ANSI": ["ansi"],
  "ANSI/AMCA": ["amca", "ansi"],
  "ANSI/ASHRAE": ["ansi", "ashrae"],
  "API": ["api"],
  "ASHRAE": ["ashrae"],
  "ASME": ["asme"],
  "ASTM": ["astm"],
  "ATN": ["adobe"],
  "Adobe": ["adobe"],
  "BCP": ["ietf"],
  "BH": ["nist"],
  "BIP": ["bsi"],
  "BIPM": ["bipm"],
  "BMS": ["nist"],
  "BS": ["bsi"],
  "BS EN": ["bsi"],
  "BS EN IEC": ["bsi"],
  "BS EN ISO": ["bsi"],
  "BS IEC": ["bsi"],
  "BS ISO": ["bsi"],
  "BSI": ["bsi"],
  "BSS": ["nist"],
  "CC": ["calconnect"],
  "CCAUV": ["bipm"],
  "CCEM": ["bipm"],
  "CCL": ["bipm"],
  "CCM": ["bipm"],
  "CCPR": ["bipm"],
  "CCQM": ["bipm"],
  "CCRI": ["bipm"],
  "CCSDS": ["ccsds"],
  "CCT": ["bipm"],
  "CCTF": ["bipm"],
  "CCU": ["bipm"],
  "CEN": ["cen_cenelec"],
  "CGPM": ["bipm"],
  "CHIPS": ["nist"],
  "CIE": ["cie"],
  "CIPM": ["bipm"],
  "CIRC": ["nist"],
  "CISPR": ["iec"],
  "CJ": ["gb"],
  "CJ/T": ["gb"],
  "CLC": ["cen_cenelec"],
  "CR": ["cen_cenelec"],
  "CRPL": ["nist"],
  "CS": ["nist"],
  "CSA": ["csa"],
  "CSM": ["nist"],
  "CSWP": ["nist"],
  "CWA": ["cen_cenelec"],
  "DB": ["gb"],
  "DB/T": ["gb"],
  "DB/Z": ["gb"],
  "DD": ["bsi"],
  "DL": ["gb"],
  "DL/T": ["gb"],
  "DOI:": ["doi"],
  "EAB": ["nist"],
  "ECMA": ["ecma"],
  "EN": ["cen_cenelec"],
  "ENV": ["cen_cenelec"],
  "EP": ["bsi"],
  "ES": ["cen_cenelec"],
  "ETSI": ["etsi"],
  "EVS": ["evs"],
  "EVS EN": ["evs"],
  "EVS EN ISO": ["evs"],
  "EVS EN ISO/IEC": ["evs"],
  "EVS-EN": ["evs"],
  "EVS-EN ISO": ["evs"],
  "EVS-EN ISO/IEC": ["evs"],
  "FIPS": ["nist"],
  "FYI": ["ietf"],
  "GB": ["gb"],
  "GB/T": ["gb"],
  "GB/Z": ["gb"],
  "GBn": ["gb"],
  "GBn/T": ["gb"],
  "GBn/Z": ["gb"],
  "GCR": ["nist"],
  "GOST": ["gost"],
  "HB": ["bsi", "gb", "nist"],
  "HB/T": ["gb"],
  "HD": ["cen_cenelec"],
  "HJ": ["gb"],
  "HJ/T": ["gb"],
  "IALA": ["iala"],
  "IANA": ["iana"],
  "IDF": ["idf"],
  "IEC": ["iec"],
  "IEC/ISO": ["iec", "iso"],
  "IECEE": ["iec"],
  "IECEx": ["iec"],
  "IECQ": ["iec"],
  "IEEE": ["ieee"],
  "IHO": ["iho"],
  "IR": ["nist"],
  "ISBN": ["isbn"],
  "ISO": ["iso"],
  "ISO/IEC": ["iec", "iso"],
  "ISO/IEC/IEEE": ["iec", "ieee", "iso"],
  "ITU": ["itu"],
  "JB": ["gb"],
  "JB/T": ["gb"],
  "JCGM": ["jcgm"],
  "JCRB": ["bipm"],
  "JG": ["gb"],
  "JG/T": ["gb"],
  "JIS": ["jis"],
  "JPCRD": ["nist"],
  "JRES": ["nist"],
  "LCIRC": ["nist"],
  "MH": ["gb"],
  "MH/T": ["gb"],
  "MONO": ["nist"],
  "MP": ["nist"],
  "Metrologia": ["bipm"],
  "NA": ["bsi"],
  "NBS": ["nist"],
  "NCSTAR": ["nist"],
  "NIST": ["nist"],
  "NSRDS": ["nist"],
  "NWIRP": ["nist"],
  "NY": ["gb"],
  "NY/T": ["gb"],
  "OASIS": ["oasis"],
  "OGC": ["ogc"],
  "OIML": ["oiml"],
  "OMG": ["omg"],
  "OWMWP": ["nist"],
  "PAS": ["bsi"],
  "PC": ["nist"],
  "PD": ["bsi"],
  "PLATEAU": ["plateau"],
  "PMG": ["easc"],
  "PP": ["bsi"],
  "QB": ["gb"],
  "QB/T": ["gb"],
  "RB": ["nist"],
  "RFC": ["ietf"],
  "RMG": ["easc"],
  "RPT": ["nist"],
  "SAE": ["sae"],
  "SIBS": ["nist"],
  "SL": ["gb"],
  "SL/T": ["gb"],
  "SP": ["nist"],
  "STD": ["ietf"],
  "T/": ["gb"],
  "TB": ["gb"],
  "TB/T": ["gb"],
  "TD": ["gb"],
  "TD/T": ["gb"],
  "TIBM": ["nist"],
  "TN": ["nist"],
  "TS": ["bsi"],
  "TTB": ["nist"],
  "UN": ["un"],
  "VTS": ["nist"],
  "W3C": ["w3c"],
  "XEP": ["xsf"],
  "YY": ["gb"],
  "YY/T": ["gb"],
  "ZB": ["gb"],
  "ZB/T": ["gb"],
  "doi:": ["doi"],
  "draft": ["ietf"],
  "ГОСТ": ["gost"],
  "ПМГ": ["easc"],
  "РМГ": ["easc"],
};
